// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT6D3rmV8vnbravekhlPBIHz-AYAsVh-4',
    appId: '1:575273105753:web:2f9b8aa99aaff31968b448',
    messagingSenderId: '575273105753',
    projectId: 'todos-f9f9c',
    authDomain: 'todos-f9f9c.firebaseapp.com',
    storageBucket: 'todos-f9f9c.firebasestorage.app',
    measurementId: 'G-4CN86NLVNX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq6OSDnes-1YOXs6Z0Ol6XD4hUpIZT3lQ',
    appId: '1:575273105753:ios:c473802714c76de468b448',
    messagingSenderId: '575273105753',
    projectId: 'todos-f9f9c',
    storageBucket: 'todos-f9f9c.firebasestorage.app',
    iosBundleId: 'com.example.todos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq6OSDnes-1YOXs6Z0Ol6XD4hUpIZT3lQ',
    appId: '1:575273105753:ios:c473802714c76de468b448',
    messagingSenderId: '575273105753',
    projectId: 'todos-f9f9c',
    storageBucket: 'todos-f9f9c.firebasestorage.app',
    iosBundleId: 'com.example.todos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT6D3rmV8vnbravekhlPBIHz-AYAsVh-4',
    appId: '1:575273105753:web:ad3ba31f0ae9cb5b68b448',
    messagingSenderId: '575273105753',
    projectId: 'todos-f9f9c',
    authDomain: 'todos-f9f9c.firebaseapp.com',
    storageBucket: 'todos-f9f9c.firebasestorage.app',
    measurementId: 'G-JNMYH8GG66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp911NFoZPu8yW-Z6lLfG7Nje-Fh-jG3s',
    appId: '1:575273105753:android:f33b2b66f17b64e168b448',
    messagingSenderId: '575273105753',
    projectId: 'todos-f9f9c',
    storageBucket: 'todos-f9f9c.firebasestorage.app',
  );

}